# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    # Run every 12h
    - cron: '0 */12 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/61bb28d5fae0db7f3e801588
